"""empty message

Revision ID: 9fb8b9396c44
Revises: 
Create Date: 2024-03-12 19:33:08.374087

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fb8b9396c44'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bolsista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cpf', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('nome_mae', sa.String(), nullable=False),
    sa.Column('pis_pasep', sa.String(), nullable=False),
    sa.Column('rg', sa.String(), nullable=False),
    sa.Column('nascimento', sa.Date(), nullable=False),
    sa.Column('dados_bancarios', sa.String(), nullable=False),
    sa.Column('cep', sa.String(), nullable=False),
    sa.Column('cidade', sa.String(), nullable=False),
    sa.Column('logradouro', sa.String(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('complemento', sa.String(), nullable=True),
    sa.Column('data_deletado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('edital',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero', sa.String(), nullable=False),
    sa.Column('data_assinatura', sa.Date(), nullable=False),
    sa.Column('duracao', sa.String(), nullable=False),
    sa.Column('nucleo_responsavel', sa.String(), nullable=False),
    sa.Column('data_deletado', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bolsa',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('modalidade', sa.String(), nullable=False),
    sa.Column('carga_horaria', sa.Integer(), nullable=False),
    sa.Column('cargo', sa.String(), nullable=False),
    sa.Column('valor', sa.Float(), nullable=False),
    sa.Column('edital_id', sa.Integer(), nullable=False),
    sa.Column('data_deletado', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['edital_id'], ['edital.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rl_bolsa_bolsista',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('bolsista_id', sa.Integer(), nullable=False),
    sa.Column('bolsa_id', sa.Integer(), nullable=False),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['bolsa_id'], ['bolsa.id'], ),
    sa.ForeignKeyConstraint(['bolsista_id'], ['bolsista.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rl_bolsa_bolsista')
    op.drop_table('bolsa')
    op.drop_table('edital')
    op.drop_table('bolsista')
    # ### end Alembic commands ###
